### ISSUE TITLE
Doesn't work if python-shell-interpreter is ipython

### ISSUE THREAD

**Issue by rrudakov** [proofit404/isortify#2]
Set configuration:
```emacs-lisp
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")
```
Open python file and call:
```
M-x isortify-buffer
```
Result is \*isortify\* buffer with ipython usage help.

Probably the reason is ipython expect extra args after "--" instead of "-"

**Comment by proofit404** [comment]
Hi, thanks for the report!

Yeh, ipython is always a problem in this case.

Do you know how to run it correctly?

**Comment by beriya** [comment]
From terminal it works with next command:
```bash
ipython -m isort -- --line-width 79 path_to_file.py
```
But i'm not sure how it will work inside emacs if i set additional args
```emacs-lisp
(setq python-shell-interpreter-args "-i --simple-prompt")
```
If i run this way
```bash
ipython -i --simple-prompt -m isort -- --line-width 79 path_to_file.py
```
sorting works, but left ipython in interactive mode.

**Comment by rhdxmr** [comment]
I just sent pull request about this issue..
https://github.com/proofit404/isortify/pull/3
